import type { TopicSeed } from "./config";

export const SEED_TOPICS: TopicSeed[] = [
  {
    title: "Como Fazer Seu Consultório Aparecer na Primeira Página do Google em 2025",
    slug: "como-dentista-aparecer-primeira-pagina-google",
    primaryKeyword: "dentista primeira página google",
    secondaryKeywords: ["seo dentista"],
    category: "SEO",
    pillar: "P1",
    searchIntent: "informational",
    outline: ["Por que 82% dos pacientes buscam dentistas no Google", "Os 3 fatores que o Google usa para ranquear consultórios", "Google Meu Negócio: o fator #1", "SEO on-page para buscas locais", "Avaliações e posicionamento", "Checklist: 10 ações para subir no Google"],
    ctaHeading: "Descubra Por Que Você Não Aparece no Google",
    ctaDescription: "Auditoria completa de SEO local do seu consultório — grátis.",
    ctaButton: "Solicitar Auditoria de SEO",
    priority: 1,
  },
  {
    title: "Cadeiras Vazias no Consultório: 7 Causas Que Ninguém Te Conta",
    slug: "cadeiras-vazias-consultorio-como-resolver",
    primaryKeyword: "cadeiras vazias consultório odontológico",
    secondaryKeywords: ["gestão dentista", "cadeiras vazias consultório odontológico dentista"],
    category: "Gestão",
    pillar: "P2",
    searchIntent: "commercial",
    outline: ["A matemática das cadeiras vazias", "Causa 1: Dependência de indicações", "Causa 2: Presença digital inexistente", "Causa 3: Google Maps mal otimizado", "Causa 4: Sem follow-up", "Causa 5: Recepção não treinada", "Causa 6: Sem campanha ativa", "Causa 7: Não aparecer em IA"],
    problemRef: "2.1 Revenue Instability",
    ctaHeading: "Descubra Quantos Pacientes Você Está Perdendo",
    ctaDescription: "Diagnóstico gratuito mostra exatamente onde estão os pacientes que você não alcança.",
    ctaButton: "Quero Meu Diagnóstico",
    priority: 1,
  },
  {
    title: "Como a Inteligência Artificial Está Mudando a Odontologia em 2025",
    slug: "inteligencia-artificial-odontologia-2025",
    primaryKeyword: "inteligência artificial odontologia",
    secondaryKeywords: ["tendências dentista", "inteligência artificial odontologia dentista"],
    category: "Tendências",
    pillar: "P3",
    searchIntent: "informational",
    outline: ["IA na busca por dentistas", "Como pacientes usam IA para escolher", "GEO: nova fronteira", "IA no diagnóstico", "Chatbots e automação", "O que fazer AGORA"],
    ctaHeading: "Seu Consultório Aparece em Respostas de IA?",
    ctaDescription: "Verificamos se ChatGPT e Gemini recomendam você — gratuitamente.",
    ctaButton: "Diagnóstico de Presença em IA",
    priority: 1,
  },
  {
    title: "Marketing para Implantes Dentários: Como Captar Pacientes de R$5k a R$20k",
    slug: "marketing-implantes-dentarios-captar-pacientes",
    primaryKeyword: "marketing implantes dentários",
    secondaryKeywords: ["implantodontia dentista", "marketing implantes dentários dentista"],
    category: "Implantodontia",
    pillar: "P4",
    searchIntent: "informational",
    outline: ["Implantes: mais lucrativo e mais difícil de vender", "Jornada do paciente de implante", "Palavras-chave que convertem", "Landing page: 6 elementos", "Google Ads vs. SEO", "Comunicar valor sem antes/depois", "Funil de nutrição"],
    problemRef: "Step C — Premium Funnel Implantes",
    ctaHeading: "Quer Captar Pacientes de Implante?",
    ctaDescription: "Estratégia personalizada de captação para implantodontistas.",
    ctaButton: "Estratégia Para Implantodontia",
    priority: 1,
  },
  {
    title: "Por Que Pacientes Questionam Seu Preço — e Como Resolver",
    slug: "valor-percebido-dentista-como-cobrar-mais",
    primaryKeyword: "como cobrar mais consultório odontológico",
    secondaryKeywords: ["estratégia dentista", "como cobrar mais consultório odontológico dentista"],
    category: "Estratégia",
    pillar: "P5",
    searchIntent: "commercial",
    outline: ["A Equação de Valor", "Resultado Desejado", "Probabilidade Percebida", "Tempo e rapidez", "Esforço do paciente", "5 formas de aumentar valor percebido", "Case: de R$3k para R$12k"],
    problemRef: "1.1 Having prices challenged",
    frameworkRef: "Hormozi Value Equation: Dream Result × PLOA ÷ (Time × Effort)",
    ctaHeading: "Reposicione Seu Valor",
    ctaDescription: "Diagnóstico gratuito do posicionamento de valor do seu consultório.",
    ctaButton: "Diagnóstico de Posicionamento",
    priority: 1,
  },
  {
    title: "Google Maps para Dentistas: 10 Passos Para Aparecer no Top 3",
    slug: "google-maps-dentista-como-aparecer-top-3",
    primaryKeyword: "Google Maps dentista como aparecer",
    secondaryKeywords: [],
    category: "Google Maps",
    pillar: "P1",
    searchIntent: "informational",
    outline: ["O pacote local do Google Maps", "Verificar perfil", "Categorias corretas", "Fotos profissionais", "Descrição otimizada", "Horários atualizados", "Posts semanais", "Gestão de avaliações", "Perguntas otimizadas", "Citações NAP", "Schema markup"],
    ctaHeading: "Seu Google Maps Está Otimizado?",
    ctaDescription: "Analisamos seu perfil do Google Maps e mostramos o que corrigir.",
    ctaButton: "Auditoria de Google Maps",
    priority: 1,
  },
  {
    title: "Por Que Seus Leads Não Aparecem na Consulta (Sistema Anti-No-Show)",
    slug: "leads-nao-aparecem-consulta-no-show-dentista",
    primaryKeyword: "no show paciente dentista como evitar",
    secondaryKeywords: ["conversão dentista"],
    category: "Conversão",
    pillar: "P2",
    searchIntent: "commercial",
    outline: ["Custo real de um no-show", "5 razões dos no-shows", "Sistema Anti-No-Show: 4 camadas", "Confirmação multicanal", "Nutrição pré-consulta", "Comprometimento financeiro", "Automação"],
    problemRef: "4.2 Leads forget the appointment",
    ctaHeading: "Implemente o Sistema Anti-No-Show",
    ctaDescription: "Reduza no-shows em até 60% com nosso sistema automatizado.",
    ctaButton: "Quero Reduzir No-Shows",
    priority: 1,
  },
  {
    title: "Como Se Tornar O Dentista Mais Respeitado da Sua Cidade",
    slug: "dentista-autoridade-como-ser-referencia",
    primaryKeyword: "dentista autoridade referência cidade",
    secondaryKeywords: ["posicionamento dentista"],
    category: "Posicionamento",
    pillar: "P5",
    searchIntent: "commercial",
    outline: ["Ser bom vs. ser percebido como o melhor", "Princípio Be Somebody", "Construir autoridade em 90 dias", "Google Reviews como indicador", "Conteúdo que demonstra expertise", "Palestras e parcerias", "Efeito composto"],
    problemRef: "5. Feeling inferior to competitors",
    frameworkRef: "Kennedy Wealth Magnet 8: Be Somebody",
    ctaHeading: "Construa Sua Autoridade Digital",
    ctaDescription: "Estratégia personalizada para se tornar referência na sua região.",
    ctaButton: "Quero Ser Referência",
    priority: 1,
  },
  {
    title: "Como Conseguir 100+ Avaliações 5 Estrelas no Google",
    slug: "avaliacoes-google-dentista-como-conseguir",
    primaryKeyword: "avaliações Google dentista como conseguir",
    secondaryKeywords: ["reputação dentista"],
    category: "Reputação",
    pillar: "P1",
    searchIntent: "informational",
    outline: ["Avaliações como fator #1 de decisão", "Momento perfeito para pedir", "Script de solicitação", "QR Code + link direto", "Automação via WhatsApp", "Responder negativas sem violar CFO", "Meta: 100 avaliações em 90 dias"],
    problemRef: "1.2 No system to generate reviews",
    ctaHeading: "Implemente o Reviews Boost System",
    ctaDescription: "Sistema automatizado para gerar avaliações 5 estrelas de forma ética.",
    ctaButton: "Quero Mais Avaliações",
    priority: 1,
  },
  {
    title: "Sua Recepção Está Perdendo Pacientes? 8 Erros Que Custam Milhares",
    slug: "recepcao-consultorio-perdendo-pacientes",
    primaryKeyword: "recepção consultório odontológico treinamento",
    secondaryKeywords: ["gestão dentista", "recepção consultório odontológico treinamento dentista"],
    category: "Gestão",
    pillar: "P2",
    searchIntent: "commercial",
    outline: ["Recepção como maior vazamento", "Não responder WhatsApp rápido", "Dar preço sem gerar valor", "Sem script de agendamento", "Sem confirmação", "Sem follow-up", "Tom de voz errado", "Não qualificar lead", "Não registrar cancelamentos"],
    problemRef: "2.4 Untrained front desk",
    ctaHeading: "Sua Recepção Está Convertendo?",
    ctaDescription: "Avaliamos o atendimento da sua recepção e criamos scripts sob medida.",
    ctaButton: "Treinamento de Conversão",
    priority: 1,
  },
  {
    title: "Marketing para Ortodontia e Invisalign: Atrair Pacientes de Qualidade",
    slug: "marketing-ortodontia-invisalign-captar-pacientes",
    primaryKeyword: "marketing ortodontia invisalign",
    secondaryKeywords: ["marketing ortodontia invisalign dentista"],
    category: "Ortodontia",
    pillar: "P4",
    searchIntent: "informational",
    outline: ["Mercado de ortodontia premium", "Competir por preço é corrida para o fundo", "Posicionamento por expertise", "Simulação 3D como conversão", "Conteúdo educativo", "Google Ads para ortodontia", "Upsell"],
    problemRef: "Step C — Premium Funnel Invisalign",
    ctaHeading: "Estratégia Para Ortodontia",
    ctaDescription: "Captação personalizada de pacientes para ortodontia e Invisalign.",
    ctaButton: "Quero Captar Pacientes de Ortodontia",
    priority: 1,
  },
  {
    title: "Publicidade Odontológica em 2025: Tudo Que o CFO Permite e Proíbe",
    slug: "regulamentacao-cfo-publicidade-odontologica-2025",
    primaryKeyword: "publicidade odontológica CFO regras 2025",
    secondaryKeywords: ["compliance dentista", "publicidade odontológica CFO regras 2025 dentista"],
    category: "Compliance",
    pillar: "P3",
    searchIntent: "informational",
    outline: ["Resoluções do CFO atualizadas", "O que PODE", "O que NÃO PODE", "Redes sociais: regras específicas", "Google Ads: compliance", "Penalidades", "Marketing efetivo dentro das regras"],
    ctaHeading: "Marketing Dentro Das Regras do CFO",
    ctaDescription: "Toda nossa estratégia é desenvolvida em conformidade com o CFO.",
    ctaButton: "Marketing em Conformidade",
    priority: 1,
  },
  {
    title: "Como Criar uma Oferta Irresistível Para Seu Consultório (Sem Desconto)",
    slug: "oferta-irresistivel-dentista-como-criar",
    primaryKeyword: "oferta irresistível consultório odontológico",
    secondaryKeywords: ["estratégia dentista", "oferta irresistível consultório odontológico dentista"],
    category: "Estratégia",
    pillar: "P5",
    searchIntent: "commercial",
    outline: ["Por que desconto destrói valor", "Grand Slam Offer", "4 componentes para dentistas", "Avaliação premium + planejamento 3D", "Empacotar valor sem reduzir preço", "Garantias que removem risco", "Bônus que aumentam valor"],
    frameworkRef: "Hormozi $100M Offers: Grand Slam Offer",
    ctaHeading: "Crie Sua Oferta Premium",
    ctaDescription: "Montamos uma oferta irresistível sob medida para seu consultório.",
    ctaButton: "Quero Uma Oferta Premium",
    priority: 1,
  },
  {
    title: "WhatsApp Business para Dentistas: Converter 3x Mais Leads",
    slug: "whatsapp-business-dentista-converter-leads",
    primaryKeyword: "WhatsApp Business dentista conversão",
    secondaryKeywords: [],
    category: "Conversão",
    pillar: "P1",
    searchIntent: "informational",
    outline: ["90% dos leads preferem WhatsApp", "Configuração profissional", "Templates de primeira mensagem", "Sequência de nutrição 4 dias", "Automação: chatbot vs. humano", "Métricas", "Integração com CRM"],
    problemRef: "2.3 No WhatsApp nurturing",
    ctaHeading: "Automatize Seu WhatsApp",
    ctaDescription: "Implementamos automação de WhatsApp que converte leads enquanto você atende.",
    ctaButton: "Quero WhatsApp Automatizado",
    priority: 1,
  },
  {
    title: "Seus Leads Não Podem Pagar? Como Atrair Pacientes de Alto Valor",
    slug: "dentista-leads-nao-podem-pagar",
    primaryKeyword: "dentista atrair pacientes alto valor",
    secondaryKeywords: ["captação dentista"],
    category: "Captação",
    pillar: "P2",
    searchIntent: "commercial",
    outline: ["Gastar com marketing e atrair errado", "Segmentação por poder aquisitivo", "Posicionamento premium", "Google Ads de alta intenção", "Landing pages que pré-qualificam", "Lead scoring automático"],
    problemRef: "2.2 Leads who can't afford",
    ctaHeading: "Atraia Pacientes Premium",
    ctaDescription: "Estratégia de captação focada em pacientes de alto valor.",
    ctaButton: "Captar Pacientes de Alto Valor",
    priority: 1,
  },
  {
    title: "Marketing para Estética Dental: Lentes de Contato e Clareamento",
    slug: "marketing-estetica-dental-lentes-contato",
    primaryKeyword: "marketing estética dental lentes de contato",
    secondaryKeywords: ["marketing estética dental lentes de contato dentista"],
    category: "Estética",
    pillar: "P4",
    searchIntent: "informational",
    outline: ["Boom da estética dental no Brasil", "Perfil do paciente", "Instagram dentro do CFO", "Google Ads para estética", "Portfolio visual", "Harmonização orofacial"],
    ctaHeading: "Estratégia Para Estética Dental",
    ctaDescription: "Captação de pacientes para lentes de contato e clareamento.",
    ctaButton: "Quero Pacientes de Estética",
    priority: 1,
  },
  {
    title: "Quanto Custa um Lead Para Dentistas? Benchmarks Reais",
    slug: "custo-por-lead-dentista-quanto-pagar",
    primaryKeyword: "custo por lead dentista preço",
    secondaryKeywords: ["dados dentista"],
    category: "Dados",
    pillar: "P3",
    searchIntent: "informational",
    outline: ["O que é CPL", "Benchmark por especialidade", "Benchmark por cidade", "Google Ads vs. Meta Ads", "Como reduzir CPL", "Custo por paciente convertido"],
    ctaHeading: "Saiba Quanto Deveria Pagar Por Lead",
    ctaDescription: "Comparamos seu CPL com benchmarks reais do mercado odontológico.",
    ctaButton: "Comparar Meu CPL",
    priority: 1,
  },
  {
    title: "Pensamento Sistêmico Para Dentistas: Por Que Seu Consultório Não Cresce",
    slug: "pensamento-sistemico-consultorio-odontologico",
    primaryKeyword: "gestão consultório odontológico crescimento",
    secondaryKeywords: ["gestão consultório odontológico crescimento dentista"],
    category: "Gestão",
    pillar: "P5",
    searchIntent: "commercial",
    outline: ["Consultório como sistema com gargalos", "Loops de reforço", "Loops de equilíbrio", "3 pontos de alavancagem", "Visibilidade digital", "Conversão da recepção", "Retenção e reativação", "Diagnosticar gargalos"],
    frameworkRef: "Meadows Thinking in Systems: feedback loops, leverage points",
    ctaHeading: "Onde Está Seu Gargalo?",
    ctaDescription: "Diagnosticamos qual gargalo está travando o crescimento do seu consultório.",
    ctaButton: "Diagnóstico de Gargalos",
    priority: 1,
  },
  {
    title: "Site Para Consultório: 12 Elementos Que Convertem Visitantes em Pacientes",
    slug: "site-consultorio-odontologico-elementos-essenciais",
    primaryKeyword: "site consultório odontológico elementos",
    secondaryKeywords: ["website dentista", "site consultório odontológico elementos dentista"],
    category: "Website",
    pillar: "P1",
    searchIntent: "informational",
    outline: ["Site mais importante que cartão", "Headline com proposta", "Prova social", "WhatsApp fixo", "Especialidades dedicadas", "Depoimentos", "Fotos profissionais", "Bio do dentista", "Formulário", "Blog", "Schema", "Velocidade", "Responsivo"],
    problemRef: "1.1 Old website damages credibility",
    ctaHeading: "Seu Site Está Convertendo?",
    ctaDescription: "Auditoria gratuita do seu site com recomendações de conversão.",
    ctaButton: "Auditoria de Site",
    priority: 1,
  },
  {
    title: "Você Ainda Depende de Indicação? Por Que Isso Está Matando Seu Consultório",
    slug: "dentista-depende-indicacao-como-mudar",
    primaryKeyword: "dentista depende indicação como captar",
    secondaryKeywords: ["captação dentista"],
    category: "Captação",
    pillar: "P2",
    searchIntent: "commercial",
    outline: ["Indicação não é sistema", "O risco quando secam", "Transição para captação ativa", "SEO local", "Google Ads", "Conteúdo", "Sistema ideal: indicação + digital"],
    problemRef: "2.1 Reliance on word-of-mouth",
    ctaHeading: "Monte Seu Sistema de Captação",
    ctaDescription: "Da dependência de indicação para um sistema previsível de captação.",
    ctaButton: "Quero Captação Previsível",
    priority: 1,
  },
  {
    title: "ROI do Marketing Digital Para Dentistas: Como Calcular e Quando Esperar",
    slug: "marketing-digital-dentista-roi-retorno-investimento",
    primaryKeyword: "ROI marketing digital dentista",
    secondaryKeywords: ["dados dentista"],
    category: "Dados",
    pillar: "P3",
    searchIntent: "informational",
    outline: ["O que é ROI", "Fórmula simples", "Benchmarks por canal", "Timeline realista", "Google Ads: retorno em 2-4 semanas", "SEO: retorno em 3-6 meses", "Dashboard simples"],
    ctaHeading: "Calcule Seu ROI Potencial",
    ctaDescription: "Mostramos o retorno projetado do marketing digital para seu consultório.",
    ctaButton: "Calcular Meu ROI",
    priority: 1,
  },
  {
    title: "O Dinheiro Está no Follow-Up: 80% dos Dentistas Perdem Pacientes",
    slug: "follow-up-pacientes-sistema-dentista",
    primaryKeyword: "follow up pacientes dentista sistema",
    secondaryKeywords: ["conversão dentista"],
    category: "Conversão",
    pillar: "P5",
    searchIntent: "commercial",
    outline: ["80% das vendas no 5º-12º contato", "Por que dentistas desistem cedo", "Sistema de 7 toques", "Templates por etapa", "Automação", "Follow-up pós-consulta"],
    problemRef: "2.3 No multi-step follow-up",
    frameworkRef: "Kennedy Wealth Magnet 12: Follow-Up",
    ctaHeading: "Implemente Follow-Up Automatizado",
    ctaDescription: "Sistema de follow-up em 7 toques que funciona enquanto você atende.",
    ctaButton: "Quero Follow-Up Automático",
    priority: 1,
  },
  {
    title: "Marketing para Odontopediatria: Captar Pais Que Procuram o Melhor Dentista",
    slug: "marketing-odontopediatria-captar-pais",
    primaryKeyword: "marketing odontopediatria dentista infantil",
    secondaryKeywords: [],
    category: "Odontopediatria",
    pillar: "P4",
    searchIntent: "informational",
    outline: ["Perfil do pai/mãe que busca", "Palavras-chave que mães digitam", "Conteúdo que gera confiança", "Google Maps: fotos do ambiente", "Instagram para odontopediatria", "Retenção semestral"],
    ctaHeading: "Atraia Mais Famílias",
    ctaDescription: "Estratégia personalizada para captação de pacientes infantis.",
    ctaButton: "Marketing Para Odontopediatria",
    priority: 1,
  },
  {
    title: "Seu Concorrente Domina o Google? 5 Estratégias Para Ultrapassá-lo",
    slug: "concorrente-dominando-google-como-competir",
    primaryKeyword: "concorrente dentista Google como superar",
    secondaryKeywords: ["seo dentista"],
    category: "SEO",
    pillar: "P2",
    searchIntent: "commercial",
    outline: ["Análise competitiva", "Vencer no Google Maps", "Google Ads acima do orgânico", "Conteúdo que rouba snippets", "Avaliações superiores", "Presença em IA"],
    problemRef: "1.3 Competitors dominating local search",
    ctaHeading: "Análise Competitiva Gratuita",
    ctaDescription: "Mostramos exatamente o que seu concorrente faz e como superá-lo.",
    ctaButton: "Analisar Meus Concorrentes",
    priority: 1,
  },
  {
    title: "Instagram para Dentistas: 15 Ideias de Conteúdo Que Convertem",
    slug: "instagram-dentista-conteudo-que-converte",
    primaryKeyword: "Instagram dentista conteúdo ideias",
    secondaryKeywords: ["redes sociais dentista"],
    category: "Redes Sociais",
    pillar: "P1",
    searchIntent: "informational",
    outline: ["Por que a maioria erra", "5 conteúdos educativos", "5 provas sociais", "5 bastidores", "Frequência ideal", "Hashtags e SEO", "Call-to-action"],
    problemRef: "1.1 Irregular posting",
    ctaHeading: "Gestão de Redes Sociais",
    ctaDescription: "Criamos e publicamos conteúdo estratégico para seu Instagram.",
    ctaButton: "Quero Gestão de Instagram",
    priority: 1,
  },
  {
    title: "7 Tendências do Marketing Odontológico em 2025",
    slug: "tendencias-marketing-odontologico-2025",
    primaryKeyword: "tendências marketing odontológico 2025",
    secondaryKeywords: ["tendências marketing odontológico 2025 dentista"],
    category: "Tendências",
    pillar: "P3",
    searchIntent: "informational",
    outline: ["GEO e IA", "Vídeo curto", "Automação WhatsApp", "SEO hiperlocal", "Pacientes pesquisando antes", "Review management", "Personalização por dados"],
    ctaHeading: "Prepare Seu Consultório Para 2025",
    ctaDescription: "Implementamos as tendências que vão definir quem cresce.",
    ctaButton: "Quero Me Preparar",
    priority: 1,
  },
  {
    title: "Medo de Investir em Marketing? Como Dentistas Superam o Bloqueio",
    slug: "dentista-medo-investir-marketing-como-superar",
    primaryKeyword: "dentista medo investir marketing",
    secondaryKeywords: ["mentalidade dentista"],
    category: "Mentalidade",
    pillar: "P5",
    searchIntent: "commercial",
    outline: ["O medo real: já tentei e não funcionou", "Por que falhou", "Marketing não é custo", "1 implante paga meses", "Reduzir risco: garantias e testes", "Histórias reais"],
    problemRef: "4. Financial Fears",
    frameworkRef: "Kennedy Wealth Magnet 5: No Fear / Hormozi: reducing risk",
    ctaHeading: "Diagnóstico Sem Risco",
    ctaDescription: "Gratuito e sem compromisso. Sem risco para você.",
    ctaButton: "Diagnóstico Gratuito",
    priority: 1,
  },
  {
    title: "Landing Page Para Dentistas: Páginas Que Convertem 3x Mais",
    slug: "landing-page-dentista-alta-conversao",
    primaryKeyword: "landing page dentista conversão",
    secondaryKeywords: [],
    category: "Conversão",
    pillar: "P1",
    searchIntent: "informational",
    outline: ["Landing page vs. site", "Estrutura em 7 seções", "Headline com resultado", "Prova social", "Como funciona", "Benefícios", "Depoimentos", "FAQ", "CTA final", "Erros comuns"],
    problemRef: "2.5 No landing page",
    ctaHeading: "Landing Page Profissional",
    ctaDescription: "Criamos landing pages de alta conversão para cada especialidade.",
    ctaButton: "Quero Landing Page",
    priority: 1,
  },
  {
    title: "Agenda Caótica? Como Organizar Para Maximizar Faturamento",
    slug: "agenda-caotica-dentista-como-organizar",
    primaryKeyword: "organizar agenda consultório odontológico",
    secondaryKeywords: ["gestão dentista", "organizar agenda consultório odontológico dentista"],
    category: "Gestão",
    pillar: "P2",
    searchIntent: "commercial",
    outline: ["Custo oculto da desorganização", "Horários nobres para alto valor", "Valor/hora por procedimento", "Blocos de agenda", "Ferramentas de agendamento", "Automação de lembretes"],
    problemRef: "2.4 Bad agenda management",
    ctaHeading: "Otimize Sua Agenda",
    ctaDescription: "Reorganizamos sua agenda para maximizar faturamento por hora.",
    ctaButton: "Quero Agenda Otimizada",
    priority: 1,
  },
  {
    title: "Marketing para Endodontia: Captar Pacientes de Emergência",
    slug: "marketing-endodontia-emergencia-dental",
    primaryKeyword: "marketing endodontia tratamento canal",
    secondaryKeywords: ["marketing endodontia tratamento canal dentista"],
    category: "Endodontia",
    pillar: "P4",
    searchIntent: "informational",
    outline: ["Paciente de urgência + medo", "Palavras-chave de emergência", "Google Ads para urgência", "Google Maps para dor", "Conteúdo educativo", "Conversão rápida"],
    ctaHeading: "Capte Pacientes de Endodontia",
    ctaDescription: "Estratégia para aparecer quando pacientes buscam com urgência.",
    ctaButton: "Marketing Para Endodontia",
    priority: 1,
  },
  {
    title: "SEO Hiperlocal: Como Dominar Buscas no Seu Bairro",
    slug: "seo-local-dentista-bairro-regiao",
    primaryKeyword: "SEO local dentista bairro",
    secondaryKeywords: [],
    category: "SEO",
    pillar: "P1",
    searchIntent: "informational",
    outline: ["'Dentista em [bairro]' converte mais", "Páginas por região", "Google Maps por bairro", "Conteúdo localizado", "Citações locais", "Cases de micro-regiões"],
    ctaHeading: "Domine as Buscas do Seu Bairro",
    ctaDescription: "SEO hiperlocal que posiciona você como referência na sua micro-região.",
    ctaButton: "Quero SEO Hiperlocal",
    priority: 2,
  },
  {
    title: "Demonstração É a Nova Publicidade: Mostre Que Você É o Melhor",
    slug: "demonstracao-resultados-dentista-marketing",
    primaryKeyword: "demonstrar resultados dentista marketing",
    secondaryKeywords: ["posicionamento dentista"],
    category: "Posicionamento",
    pillar: "P5",
    searchIntent: "commercial",
    outline: ["'Somos os melhores' não convence", "Poder da demonstração", "5 formas sem violar CFO", "Vídeos educativos", "Dados e métricas", "Cases contextualizados"],
    frameworkRef: "Kennedy Wealth Magnet 11: Demonstration",
    ctaHeading: "Construa Sua Estratégia de Demonstração",
    ctaDescription: "Mostramos como demonstrar expertise de forma convincente.",
    ctaButton: "Quero Demonstrar Resultados",
    priority: 2,
  },
  {
    title: "Pacientes Somem Depois da Primeira Consulta? Como Trazê-los de Volta",
    slug: "dentista-pacientes-somem-depois-primeira-consulta",
    primaryKeyword: "paciente some depois primeira consulta",
    secondaryKeywords: ["retenção dentista", "paciente some depois primeira consulta dentista"],
    category: "Retenção",
    pillar: "P2",
    searchIntent: "commercial",
    outline: ["Custo de adquirir vs. reter", "5 razões que não voltam", "Sistema de reativação", "WhatsApp automático semestral", "Programa VIP", "Follow-up pós-tratamento"],
    problemRef: "3.1 Patients disappearing",
    ctaHeading: "Reative Seus Pacientes Inativos",
    ctaDescription: "Sistema de reativação que traz pacientes de volta automaticamente.",
    ctaButton: "Quero Reativar Pacientes",
    priority: 2,
  },
  {
    title: "8 Erros em Google Ads Que Desperdiçam R$3.000/Mês",
    slug: "google-ads-dentista-erros-que-desperdicam-dinheiro",
    primaryKeyword: "Google Ads dentista erros dinheiro",
    secondaryKeywords: [],
    category: "Ads",
    pillar: "P3",
    searchIntent: "informational",
    outline: ["Sem palavras-chave negativas", "Landing page genérica", "Sem extensões", "Sem separar campanhas", "Orçamento espalhado", "Sem rastrear conversões", "Copiar concorrente", "Desistir cedo"],
    ctaHeading: "Auditoria de Google Ads",
    ctaDescription: "Encontramos onde seus anúncios estão desperdiçando dinheiro.",
    ctaButton: "Auditoria Gratuita de Ads",
    priority: 2,
  },
  {
    title: "Marketing para Periodontia: Educar Pacientes Que Não Sabem Que Precisam",
    slug: "marketing-periodontia-educar-pacientes",
    primaryKeyword: "marketing periodontia pacientes",
    secondaryKeywords: ["marketing periodontia pacientes dentista"],
    category: "Periodontia",
    pillar: "P4",
    searchIntent: "informational",
    outline: ["50% dos adultos têm doença periodontal", "Conteúdo educativo como funil", "SEO para sintomas", "Parcerias com clínicos gerais", "Consulta em tratamento recorrente", "Receita recorrente"],
    ctaHeading: "Estratégia Para Periodontia",
    ctaDescription: "Captação de pacientes para periodontia através de educação digital.",
    ctaButton: "Marketing Para Periodontia",
    priority: 2,
  },
  {
    title: "Meta Ads Para Dentistas: Campanhas no Facebook e Instagram",
    slug: "meta-ads-dentista-facebook-instagram",
    primaryKeyword: "Facebook Ads Instagram Ads dentista",
    secondaryKeywords: [],
    category: "Ads",
    pillar: "P1",
    searchIntent: "informational",
    outline: ["Quando usar Meta vs. Google", "Estrutura de campanha", "Criativos respeitando CFO", "Segmentação e lookalike", "Retargeting", "Orçamento por especialidade"],
    ctaHeading: "Campanhas de Meta Ads",
    ctaDescription: "Criamos campanhas no Facebook e Instagram que geram pacientes reais.",
    ctaButton: "Quero Meta Ads",
    priority: 2,
  },
  {
    title: "Como Cobrar Mais Sem Perder Pacientes: Precificação Para Dentistas",
    slug: "dentista-cobrar-mais-sem-perder-pacientes",
    primaryKeyword: "dentista cobrar mais precificação",
    secondaryKeywords: ["gestão dentista"],
    category: "Gestão",
    pillar: "P2",
    searchIntent: "commercial",
    outline: ["Medo de cobrar", "Precificação por valor vs. custo", "Aumentar preço gradualmente", "Comunicação de valor", "Pacotes e bundles", "Financiamento como ferramenta"],
    problemRef: "2.1 Underpricing",
    ctaHeading: "Reposicione Seu Preço",
    ctaDescription: "Estratégia de precificação que aumenta ticket sem perder pacientes.",
    ctaButton: "Quero Cobrar Mais",
    priority: 2,
  },
  {
    title: "Escassez e Urgência Ética: Exclusividade Para Lotar Sua Agenda",
    slug: "escassez-urgencia-consultorio-odontologico",
    primaryKeyword: "escassez urgência marketing dentista",
    secondaryKeywords: ["estratégia dentista"],
    category: "Estratégia",
    pillar: "P5",
    searchIntent: "commercial",
    outline: ["Psicologia da escassez", "Escassez real vs. fabricada", "Exclusividade territorial", "Vagas limitadas", "Promoções com deadline", "Comunicar sem parecer desespero"],
    frameworkRef: "Hormozi: Scarcity, Urgency, Guarantees",
    ctaHeading: "Aplique Escassez Ética",
    ctaDescription: "Modelo de exclusividade territorial que gera urgência genuína.",
    ctaButton: "Verificar Disponibilidade",
    priority: 2,
  },
  {
    title: "ChatGPT Está Recomendando Dentistas — Você Está Entre Eles?",
    slug: "chatgpt-recomendando-dentistas-como-aparecer",
    primaryKeyword: "ChatGPT recomenda dentista como aparecer",
    secondaryKeywords: ["geo dentista"],
    category: "GEO",
    pillar: "P3",
    searchIntent: "informational",
    outline: ["Teste: pergunte ao ChatGPT", "Como ChatGPT escolhe", "Fatores que influenciam", "3 ações para ser citado em 60 dias", "Schema markup", "Futuro: 40% das buscas por IA"],
    ctaHeading: "Apareça em Respostas de IA",
    ctaDescription: "Otimizamos sua presença para ser recomendado por ChatGPT e Gemini.",
    ctaButton: "Diagnóstico de IA",
    priority: 2,
  },
  {
    title: "E-mail Marketing Para Dentistas: Reativar Pacientes e Gerar Retorno",
    slug: "email-marketing-dentista-reativacao-pacientes",
    primaryKeyword: "email marketing dentista reativação",
    secondaryKeywords: ["retenção dentista"],
    category: "Retenção",
    pillar: "P1",
    searchIntent: "informational",
    outline: ["E-mail ainda funciona", "Segmentação", "Sequência de reativação 5 e-mails", "Newsletter mensal", "Automação semestral", "Templates prontos"],
    problemRef: "4.4 No reactivation campaigns",
    ctaHeading: "Reative Sua Base de Pacientes",
    ctaDescription: "E-mail automatizado que traz pacientes de volta sem esforço.",
    ctaButton: "Quero Reativação Automática",
    priority: 2,
  },
  {
    title: "Marketing para Harmonização Orofacial: Pacientes de Estética Premium",
    slug: "marketing-harmonizacao-orofacial-captar-pacientes",
    primaryKeyword: "marketing harmonização orofacial",
    secondaryKeywords: ["estética dentista", "marketing harmonização orofacial dentista"],
    category: "Estética",
    pillar: "P4",
    searchIntent: "informational",
    outline: ["Mercado de HOF no Brasil", "Posicionamento: natural vs. exagero", "Perfil do paciente", "Conteúdo visual no Instagram", "Google Ads para HOF", "Simulação digital", "Upsell"],
    problemRef: "Step C — Premium Funnel HOF",
    ctaHeading: "Estratégia Para Harmonização",
    ctaDescription: "Captação de pacientes para harmonização orofacial premium.",
    ctaButton: "Marketing Para HOF",
    priority: 2,
  },
  {
    title: "Burnout no Consultório: Trabalhar Menos e Faturar Mais",
    slug: "dentista-burnout-trabalho-demais-como-resolver",
    primaryKeyword: "dentista burnout trabalhar menos faturar mais",
    secondaryKeywords: ["gestão dentista"],
    category: "Gestão",
    pillar: "P2",
    searchIntent: "commercial",
    outline: ["Epidemia de burnout", "Trabalhar mais não é resposta", "Mais procedimentos de alto valor", "Automação", "Delegação e treinamento", "Modelo: 4 dias/semana premium", "Case real"],
    problemRef: "6. Constant stress and burnout",
    frameworkRef: "Hormozi: Reducing Effort & Sacrifice",
    ctaHeading: "Redesenhe Sua Operação",
    ctaDescription: "Consultoria para trabalhar menos horas com mais faturamento.",
    ctaButton: "Quero Trabalhar Menos",
    priority: 2,
  },
  {
    title: "CRM Para Dentistas: Gerenciar Leads e Pacientes Sem Perder Nenhum",
    slug: "crm-dentista-gestao-pacientes-leads",
    primaryKeyword: "CRM dentista gestão pacientes",
    secondaryKeywords: ["ferramentas dentista"],
    category: "Ferramentas",
    pillar: "P1",
    searchIntent: "informational",
    outline: ["O que é CRM", "3 funções essenciais", "CRMs recomendados", "Pipeline de leads", "Automação", "Métricas no dashboard"],
    problemRef: "2.4 No CRM",
    ctaHeading: "Implemente CRM",
    ctaDescription: "Sistema de CRM configurado para consultórios odontológicos.",
    ctaButton: "Quero CRM no Consultório",
    priority: 2,
  },
  {
    title: "Mentalidade de Abundância: O Que Separa Dentistas de R$50k e R$200k/Mês",
    slug: "atracao-riqueza-dentista-mentalidade-crescimento",
    primaryKeyword: "dentista mentalidade crescimento faturamento",
    secondaryKeywords: [],
    category: "Mentalidade",
    pillar: "P5",
    searchIntent: "commercial",
    outline: ["Escassez vs. abundância", "Por que talentosos ficam presos", "Pare de comprar narrativas negativas", "Como os de sucesso pensam", "Investir em crescimento", "5 mudanças de mentalidade"],
    frameworkRef: "Kennedy Wealth Magnet 2: Belief in Abundance",
    ctaHeading: "Desbloqueie Seu Crescimento",
    ctaDescription: "Diagnóstico que mostra o potencial de faturamento do seu consultório.",
    ctaButton: "Desbloquear Crescimento",
    priority: 2,
  },
  {
    title: "Branding Para Dentistas: Marca Que Cobra Premium e Atrai Valor",
    slug: "dentista-branding-marca-premium",
    primaryKeyword: "branding dentista marca premium",
    secondaryKeywords: ["posicionamento dentista"],
    category: "Posicionamento",
    pillar: "P2",
    searchIntent: "commercial",
    outline: ["Ter logo vs. ter marca", "Visual que transmite premium", "Tom de voz", "Consistência multi-canal", "Case: rebranding +40% ticket", "8 elementos de marca forte"],
    problemRef: "1.1 Lack of brand identity",
    ctaHeading: "Eleve Sua Marca",
    ctaDescription: "Construímos marcas odontológicas que justificam preço premium.",
    ctaButton: "Quero Marca Premium",
    priority: 2,
  },
  {
    title: "TikTok e Reels Para Dentistas: Vale a Pena?",
    slug: "tiktok-reels-dentista-vale-a-pena",
    primaryKeyword: "TikTok Reels dentista",
    secondaryKeywords: ["redes sociais dentista"],
    category: "Redes Sociais",
    pillar: "P3",
    searchIntent: "informational",
    outline: ["Pacientes jovens usam TikTok", "O que funciona", "O que CFO proíbe", "Formatos com engajamento", "Frequência", "ROI: traz pacientes?"],
    ctaHeading: "Estratégia de Vídeo",
    ctaDescription: "Criamos conteúdo de vídeo curto que atrai pacientes — dentro do CFO.",
    ctaButton: "Quero Vídeos",
    priority: 2,
  },
  {
    title: "Marketing para Prótese Dentária: Alcançar Pacientes de Reabilitação",
    slug: "marketing-protese-dentaria-pacientes-idosos",
    primaryKeyword: "marketing prótese dentária reabilitação oral",
    secondaryKeywords: ["marketing prótese dentária reabilitação oral dentista"],
    category: "Prótese",
    pillar: "P4",
    searchIntent: "informational",
    outline: ["Perfil do paciente: necessidade + vergonha", "Linguagem empática", "Google Ads para reabilitação", "Conteúdo educativo", "Google Maps", "Financiamento"],
    ctaHeading: "Capte Pacientes de Prótese",
    ctaDescription: "Estratégia de captação para prótese e reabilitação oral.",
    ctaButton: "Marketing Para Prótese",
    priority: 2,
  },
  {
    title: "Schema Markup Para Dentistas: O SEO Técnico Que 95% Ignoram",
    slug: "schema-markup-dentista-seo-tecnico",
    primaryKeyword: "schema markup dentista SEO técnico",
    secondaryKeywords: [],
    category: "SEO",
    pillar: "P1",
    searchIntent: "informational",
    outline: ["O que é schema e por que Google ama", "5 schemas essenciais", "LocalBusiness/Dentist", "FAQPage", "HowTo", "Review schema", "Ferramentas de validação"],
    ctaHeading: "Implemente Schema No Seu Site",
    ctaDescription: "Schema markup configurado por especialistas em SEO odontológico.",
    ctaButton: "Quero Schema Markup",
    priority: 2,
  },
  {
    title: "Como Fazer Estranhos Quererem Agendar Com Você",
    slug: "leads-estranhos-dentista-como-atrair",
    primaryKeyword: "captação pacientes odontológicos estratégia",
    secondaryKeywords: ["captação pacientes odontológicos estratégia dentista"],
    category: "Captação",
    pillar: "P5",
    searchIntent: "commercial",
    outline: ["4 métodos fundamentais", "Warm outreach", "Cold outreach", "Content", "Paid ads", "Escolher o método certo", "Combinar múltiplos canais"],
    frameworkRef: "Hormozi $100M Leads: Core 4",
    ctaHeading: "Monte Sua Estratégia de Captação",
    ctaDescription: "Os 4 métodos de captação aplicados à odontologia.",
    ctaButton: "Quero Captação Completa",
    priority: 2,
  },
  {
    title: "Script de Venda: Como Sua Equipe Pode Converter 2x Mais",
    slug: "script-venda-consultorio-dentista",
    primaryKeyword: "script venda consultório dentista",
    secondaryKeywords: ["conversão dentista"],
    category: "Conversão",
    pillar: "P2",
    searchIntent: "commercial",
    outline: ["Improviso mata vendas", "Script WhatsApp", "Script telefone", "Script follow-up", "Script objeções", "Treinar sem ser robótico", "Templates para download"],
    problemRef: "2.3 No scripts",
    ctaHeading: "Scripts Para Sua Equipe",
    ctaDescription: "Scripts de venda testados e prontos para sua recepção usar.",
    ctaButton: "Quero Scripts Prontos",
    priority: 2,
  },
  {
    title: "Mercado Odontológico Brasileiro em 2025: Dados e Oportunidades",
    slug: "dados-mercado-odontologico-brasil-2025",
    primaryKeyword: "mercado odontológico Brasil 2025 dados",
    secondaryKeywords: ["mercado odontológico Brasil 2025 dados dentista"],
    category: "Dados",
    pillar: "P3",
    searchIntent: "informational",
    outline: ["Número de dentistas no Brasil", "Faturamento por especialidade", "Cidades: demanda vs. oferta", "Procedimentos mais buscados", "Tendências de preço", "Oportunidades inexploradas"],
    ctaHeading: "Análise do Mercado Na Sua Região",
    ctaDescription: "Dados de mercado específicos para sua cidade e especialidade.",
    ctaButton: "Análise de Mercado",
    priority: 2,
  },
  {
    title: "Medir Resultados do Marketing: As 7 Métricas Que Importam",
    slug: "como-medir-resultados-marketing-dentista",
    primaryKeyword: "medir resultados marketing dentista métricas",
    secondaryKeywords: ["dados dentista"],
    category: "Dados",
    pillar: "P1",
    searchIntent: "informational",
    outline: ["Curtidas não pagam contas", "CPL", "Taxa de conversão", "Show rate", "Custo por paciente", "Ticket médio", "LTV", "ROI por canal"],
    problemRef: "2.5 Poor tracking",
    ctaHeading: "Dashboard de Métricas",
    ctaDescription: "Configuramos um dashboard com as métricas que realmente importam.",
    ctaButton: "Quero Meu Dashboard",
    priority: 2,
  },
  {
    title: "Marketing Para Clínicas Multidisciplinares: Sem Diluir a Mensagem",
    slug: "marketing-clinica-odontologica-multiespecialidade",
    primaryKeyword: "marketing clínica odontológica multiespecialidade",
    secondaryKeywords: ["estratégia dentista", "marketing clínica odontológica multiespecialidade dentista"],
    category: "Estratégia",
    pillar: "P4",
    searchIntent: "informational",
    outline: ["Promover tudo = promover nada", "Serviço âncora", "Páginas por especialidade", "Campanhas separadas", "Cross-sell inteligente", "Google Maps multi"],
    ctaHeading: "Estratégia Para Clínica Multi",
    ctaDescription: "Marketing estruturado para clínicas com múltiplas especialidades.",
    ctaButton: "Quero Estratégia Multi",
    priority: 2,
  },
  {
    title: "Garantias Que Vendem: Remover Medo e Aumentar Conversão",
    slug: "garantias-consultorio-odontologico-confianca",
    primaryKeyword: "garantia consultório odontológico conversão",
    secondaryKeywords: ["garantia consultório odontológico conversão dentista"],
    category: "Conversão",
    pillar: "P5",
    searchIntent: "commercial",
    outline: ["Medo é maior que desejo", "Tipos de garantia para odontologia", "Satisfação com planejamento", "Garantia condicional", "Pós-operatório assistido", "Comunicar sem prometer resultado (CFO)", "Impacto na conversão"],
    frameworkRef: "Hormozi: Guarantees",
    ctaHeading: "Implemente Garantias Inteligentes",
    ctaDescription: "Garantias que aumentam conversão sem risco regulatório.",
    ctaButton: "Quero Garantias",
    priority: 2,
  },
  {
    title: "Sua Equipe Não Funciona? Como Alinhar Para Crescer",
    slug: "dentista-equipe-nao-funciona-como-resolver",
    primaryKeyword: "equipe consultório odontológico treinamento",
    secondaryKeywords: ["gestão dentista", "equipe consultório odontológico treinamento dentista"],
    category: "Gestão",
    pillar: "P2",
    searchIntent: "commercial",
    outline: ["Equipe desalinhada e faturamento", "Recepção: gargalo #1", "Scripts e protocolos", "Reuniões de 15 minutos", "Métricas por pessoa", "Accountability sem conflito"],
    problemRef: "3.2 Staff not following scripts",
    ctaHeading: "Alinhe Sua Equipe",
    ctaDescription: "Treinamento e scripts para recepção e assistentes.",
    ctaButton: "Quero Equipe Alinhada",
    priority: 2,
  },
  {
    title: "Google Ads vs. SEO Para Dentistas: Qual Investir Primeiro?",
    slug: "google-ads-vs-seo-dentista-qual-melhor",
    primaryKeyword: "Google Ads vs SEO dentista",
    secondaryKeywords: ["estratégia dentista"],
    category: "Estratégia",
    pillar: "P1",
    searchIntent: "informational",
    outline: ["Depende do momento", "Ads: resultado rápido custo contínuo", "SEO: resultado demorado retorno crescente", "Comparação por especialidade", "Cenário ideal: ambos", "Dividir orçamento", "Timeline realista"],
    ctaHeading: "Estratégia Combinada",
    ctaDescription: "Ads + SEO trabalhando juntos para máximo retorno.",
    ctaButton: "Quero Ads + SEO",
    priority: 2,
  },
  {
    title: "Perplexity e Gemini: As Novas Buscas de IA Para Dentistas",
    slug: "perplexity-gemini-dentista-como-aparecer",
    primaryKeyword: "Perplexity Gemini dentista IA busca",
    secondaryKeywords: ["geo dentista"],
    category: "GEO",
    pillar: "P3",
    searchIntent: "informational",
    outline: ["Além do Google", "Como funciona cada plataforma", "Diferenças entre IAs", "Otimizando para Perplexity", "Otimizando para Gemini", "Checklist: 5 ações"],
    ctaHeading: "Presença em Todas as IAs",
    ctaDescription: "Otimização para todas as plataformas de busca por IA.",
    ctaButton: "Quero Presença em IA",
    priority: 2,
  },
  {
    title: "Fale a Linguagem do Dinheiro: Como Dentistas de Sucesso Pensam",
    slug: "dentista-falar-linguagem-dinheiro",
    primaryKeyword: "dentista investimento marketing retorno",
    secondaryKeywords: ["mentalidade dentista"],
    category: "Mentalidade",
    pillar: "P5",
    searchIntent: "commercial",
    outline: ["Linguagem que separa quem cresce", "De custo para investimento", "De gastar para ROI", "Valor do paciente em 5 anos", "A conta antes de investir", "Mentalidade de investidor"],
    frameworkRef: "Kennedy Wealth Magnet 7: Speak Money",
    ctaHeading: "Pense Como Investidor",
    ctaDescription: "Diagnóstico com projeção de ROI para seu consultório.",
    ctaButton: "Quero Projeção de ROI",
    priority: 2,
  },
  {
    title: "Pacientes Só Perguntam Preço? Como Mudar Para Valor",
    slug: "pacientes-so-querem-preco-como-lidar",
    primaryKeyword: "paciente pergunta preço dentista",
    secondaryKeywords: ["conversão dentista"],
    category: "Conversão",
    pillar: "P2",
    searchIntent: "commercial",
    outline: ["Por que perguntam preço", "Erro: responder com número", "Técnica de redirecionamento", "Script para WhatsApp", "Pré-qualificar na landing page", "Posicionamento que atrai qualidade"],
    problemRef: "2.2 Leads looking for quotes / 1.1 Prices challenged",
    ctaHeading: "Converta Leads de Preço",
    ctaDescription: "Scripts que transformam perguntas de preço em agendamentos.",
    ctaButton: "Quero Converter Leads",
    priority: 2,
  },
  {
    title: "Marketing Para Dentista Clínico Geral: Competir Quando Todos São Iguais",
    slug: "marketing-dentista-clinico-geral",
    primaryKeyword: "marketing dentista clínico geral diferenciação",
    secondaryKeywords: [],
    category: "Clínico Geral",
    pillar: "P4",
    searchIntent: "informational",
    outline: ["Desafio: parecer 'mais do mesmo'", "Diferenciação", "SEO local para buscas genéricas", "Google Maps como arma", "Conteúdo mostrando expertise", "Cross-referral com especialistas"],
    ctaHeading: "Diferencie Sua Clínica Geral",
    ctaDescription: "Posicionamento que diferencia seu consultório da concorrência.",
    ctaButton: "Quero Me Diferenciar",
    priority: 2,
  },
  {
    title: "Automação de Marketing: 5 Ferramentas Que Trabalham Por Você",
    slug: "automacao-marketing-dentista-ferramentas",
    primaryKeyword: "automação marketing dentista ferramentas",
    secondaryKeywords: [],
    category: "Ferramentas",
    pillar: "P1",
    searchIntent: "informational",
    outline: ["Marketing sem intervenção", "WhatsApp API + chatbot", "Google Meu Negócio auto-posts", "E-mail automatizado", "CRM com pipeline", "Agendamento online", "Integrar tudo"],
    problemRef: "2.4 Manual processes",
    ctaHeading: "Automatize Seu Marketing",
    ctaDescription: "5 automações implementadas para seu consultório.",
    ctaButton: "Quero Automação",
    priority: 3,
  },
  {
    title: "Marketing Digital Para Saúde no Brasil: Regulamentação e Oportunidades",
    slug: "marketing-saude-digital-brasil-regulamentacao",
    primaryKeyword: "marketing digital saúde Brasil regulamentação",
    secondaryKeywords: ["compliance dentista", "marketing digital saúde Brasil regulamentação dentista"],
    category: "Compliance",
    pillar: "P3",
    searchIntent: "informational",
    outline: ["Cenário regulatório", "CFO vs. CFM", "LGPD e dados de pacientes", "Ética na publicidade", "O que outros países fazem", "Oportunidades dentro das regras"],
    ctaHeading: "Marketing Ético e Efetivo",
    ctaDescription: "Estratégia em conformidade com todas as regulamentações.",
    ctaButton: "Quero Conformidade",
    priority: 3,
  },
  {
    title: "Oportunismo Estratégico: Aproveitar Oportunidades Que Outros Ignoram",
    slug: "dentista-oportunidade-mercado-como-aproveitar",
    primaryKeyword: "dentista oportunidade mercado crescimento",
    secondaryKeywords: ["estratégia dentista"],
    category: "Estratégia",
    pillar: "P5",
    searchIntent: "commercial",
    outline: ["Oportunismo é inteligência", "Presença em IA", "Dominar Google Maps no bairro", "Especializar quando todos generalizam", "Automação para escalar", "Identificar oportunidades antes"],
    frameworkRef: "Kennedy Wealth Magnet 4: Opportunism",
    ctaHeading: "Identifique Oportunidades",
    ctaDescription: "Análise de oportunidades inexploradas na sua região.",
    ctaButton: "Quero Ver Oportunidades",
    priority: 3,
  },
  {
    title: "Financiamento de Tratamentos: Oferecer Sem Comprometer Seu Caixa",
    slug: "financiamento-tratamento-dentario-como-oferecer",
    primaryKeyword: "financiamento tratamento dentário",
    secondaryKeywords: ["gestão dentista", "financiamento tratamento dentário dentista"],
    category: "Gestão",
    pillar: "P2",
    searchIntent: "commercial",
    outline: ["Impacto na conversão", "Parcelamento próprio vs. financeiras", "Comunicar na landing page", "Margem vs. volume", "Plataformas para saúde", "Scripts de apresentação"],
    problemRef: "Step C: Financiamento 12x",
    ctaHeading: "Aumente Conversão Com Financiamento",
    ctaDescription: "Implementamos opções de financiamento que aumentam conversão.",
    ctaButton: "Quero Financiamento",
    priority: 3,
  },
  {
    title: "Blog Para Dentistas: 30 Ideias de Artigos Que Atraem Pacientes",
    slug: "conteudo-blog-dentista-o-que-escrever",
    primaryKeyword: "blog dentista ideias artigos SEO",
    secondaryKeywords: ["conteúdo dentista"],
    category: "Conteúdo",
    pillar: "P1",
    searchIntent: "informational",
    outline: ["Blog ainda funciona", "10 artigos informacionais", "10 artigos comerciais", "10 artigos de decisão", "Estrutura ideal", "Frequência", "SEO checklist"],
    ctaHeading: "Gestão de Conteúdo",
    ctaDescription: "Criamos e publicamos artigos que atraem pacientes via Google.",
    ctaButton: "Quero Blog Profissional",
    priority: 3,
  },
  {
    title: "Marketing Para Dentistas em Cidades Pequenas: Estratégias Que Funcionam",
    slug: "marketing-dentista-rural-cidades-pequenas",
    primaryKeyword: "marketing dentista cidade pequena interior",
    secondaryKeywords: ["estratégia dentista"],
    category: "Estratégia",
    pillar: "P4",
    searchIntent: "informational",
    outline: ["Menos concorrência = mais oportunidade", "Google Maps dominante", "SEO local rápido", "Instagram como canal", "Parcerias locais", "Google Ads com orçamento reduzido"],
    ctaHeading: "Marketing Para Interior",
    ctaDescription: "Estratégias adaptadas para cidades pequenas e médias.",
    ctaButton: "Quero Marketing Local",
    priority: 3,
  },
  {
    title: "Sem Desculpas: Nenhuma Justificativa Salva Seu Consultório",
    slug: "dentista-sem-desculpas-crescimento",
    primaryKeyword: "dentista crescimento consultório estagnação",
    secondaryKeywords: ["mentalidade dentista"],
    category: "Mentalidade",
    pillar: "P5",
    searchIntent: "commercial",
    outline: ["As desculpas mais comuns", "Cidade pequena demais", "Marketing não funciona", "Já tentei", "Não tenho tempo", "Meus pacientes são indicação", "Cada desculpa tem solução"],
    frameworkRef: "Kennedy Wealth Magnet 6: No Excuses",
    ctaHeading: "Quebre o Ciclo",
    ctaDescription: "O primeiro passo é o diagnóstico — gratuito e sem compromisso.",
    ctaButton: "Quero Começar Agora",
    priority: 3,
  },
  {
    title: "Parcerias Estratégicas: Redes de Indicação Que Geram Pacientes",
    slug: "parcerias-estrategicas-dentista-indicacoes",
    primaryKeyword: "parcerias estratégicas dentista referral",
    secondaryKeywords: ["captação dentista"],
    category: "Captação",
    pillar: "P2",
    searchIntent: "commercial",
    outline: ["Indicação estruturada vs. espontânea", "Parcerias com profissionais de saúde", "Convênio corporativo", "Programa de indicação para pacientes", "Incentivos éticos", "Formalizar e rastrear"],
    problemRef: "3.3 Weak referral partnerships",
    ctaHeading: "Monte Sua Rede de Parcerias",
    ctaDescription: "Sistema de parcerias que gera indicações previsíveis.",
    ctaButton: "Quero Parcerias",
    priority: 3,
  },
  {
    title: "SEO Técnico Para Consultórios: 8 Ajustes Que o Google Adora",
    slug: "seo-tecnico-consultorio-odontologico",
    primaryKeyword: "SEO técnico consultório odontológico",
    secondaryKeywords: ["SEO técnico consultório odontológico dentista"],
    category: "SEO",
    pillar: "P1",
    searchIntent: "informational",
    outline: ["O que é SEO técnico", "Velocidade (Core Web Vitals)", "Mobile-first", "HTTPS", "Sitemap e robots.txt", "Schema markup", "URLs amigáveis", "Erros 404"],
    ctaHeading: "Auditoria Técnica",
    ctaDescription: "Verificamos e corrigimos problemas técnicos de SEO no seu site.",
    ctaButton: "Auditoria de SEO Técnico",
    priority: 3,
  },
  {
    title: "YouTube Para Dentistas: Vídeos Que Atraem (Sem Ser YouTuber)",
    slug: "video-marketing-dentista-youtube",
    primaryKeyword: "YouTube dentista vídeos marketing",
    secondaryKeywords: ["conteúdo dentista"],
    category: "Conteúdo",
    pillar: "P3",
    searchIntent: "informational",
    outline: ["YouTube: 2ª maior busca", "Tipos de vídeo que funcionam", "Equipamento mínimo", "SEO no YouTube", "Compliance CFO", "1 vídeo → 5 peças de conteúdo"],
    ctaHeading: "Estratégia de Vídeo",
    ctaDescription: "Produzimos conteúdo de vídeo estratégico para seu consultório.",
    ctaButton: "Quero Vídeos",
    priority: 3,
  },
  {
    title: "Invisível Online? Plano de 30 Dias Para Aparecer",
    slug: "dentista-nao-aparece-online-como-resolver",
    primaryKeyword: "dentista não aparece Google como resolver",
    secondaryKeywords: ["visibilidade dentista"],
    category: "Visibilidade",
    pillar: "P2",
    searchIntent: "commercial",
    outline: ["Diagnóstico: por que não aparece", "Semana 1: Google Meu Negócio", "Semana 2: SEO básico", "Semana 3: avaliações e citações", "Semana 4: conteúdo + Ads", "De invisível para top 3"],
    problemRef: "5. Feeling forgotten online",
    ctaHeading: "Saia Da Invisibilidade",
    ctaDescription: "Plano de 30 dias para colocar seu consultório no mapa digital.",
    ctaButton: "Quero Aparecer Online",
    priority: 3,
  },
  {
    title: "Marketing Para Clínicas Populares: Volume Sem Depender Só de Preço",
    slug: "marketing-clinica-popular-baixo-custo",
    primaryKeyword: "marketing clínica popular odontológica",
    secondaryKeywords: ["estratégia dentista", "marketing clínica popular odontológica dentista"],
    category: "Estratégia",
    pillar: "P4",
    searchIntent: "informational",
    outline: ["Modelo popular: volume + acessibilidade", "Diferenciação além de preço", "Google Maps principal", "Anúncios de acessibilidade", "Operação eficiente", "Fidelização primeira consulta"],
    ctaHeading: "Estratégia Para Clínica Popular",
    ctaDescription: "Marketing que gera volume sem comprometer margem.",
    ctaButton: "Quero Volume de Pacientes",
    priority: 3,
  },
  {
    title: "Esteja Em Algum Lugar: Dentistas Invisíveis Perdem a Guerra",
    slug: "dentista-esteja-em-algum-lugar-presenca-digital",
    primaryKeyword: "dentista presença digital importância",
    secondaryKeywords: ["posicionamento dentista"],
    category: "Posicionamento",
    pillar: "P5",
    searchIntent: "commercial",
    outline: ["Se não te encontram não existe", "5 lugares obrigatórios", "Google Maps", "Site otimizado", "Instagram", "Plataformas de IA", "Priorizar com orçamento limitado"],
    frameworkRef: "Kennedy Wealth Magnet 9: Be Somewhere",
    ctaHeading: "Construa Sua Presença Digital",
    ctaDescription: "Os 5 canais onde todo dentista precisa estar — implementados para você.",
    ctaButton: "Quero Presença Digital",
    priority: 3,
  },
  {
    title: "Retargeting: Alcançar Quem Visitou Seu Site Mas Não Agendou",
    slug: "retargeting-dentista-anuncios-remarketing",
    primaryKeyword: "retargeting remarketing dentista",
    secondaryKeywords: ["ads dentista"],
    category: "Ads",
    pillar: "P1",
    searchIntent: "informational",
    outline: ["O que é retargeting", "96% não convertem na primeira vez", "Meta Ads retargeting", "Google Ads retargeting", "Criativos que convertem", "Orçamento para remarketing"],
    ctaHeading: "Implemente Retargeting",
    ctaDescription: "Campanhas de retargeting que recuperam visitantes perdidos.",
    ctaButton: "Quero Retargeting",
    priority: 3,
  },
  {
    title: "Gerenciamento de Expectativas: Evitar Avaliações Negativas",
    slug: "expectativa-paciente-resultado-como-gerenciar",
    primaryKeyword: "gerenciar expectativa paciente dentista",
    secondaryKeywords: ["reputação dentista"],
    category: "Reputação",
    pillar: "P2",
    searchIntent: "commercial",
    outline: ["Causa #1 de insatisfação", "Momento de alinhar", "Técnicas de comunicação", "Consentimento informado", "Follow-up pós-procedimento", "Quando algo dá errado"],
    problemRef: "4.3 No expectation management",
    ctaHeading: "Previna Avaliações Negativas",
    ctaDescription: "Sistema de gestão de expectativas que previne problemas.",
    ctaButton: "Quero Prevenir Problemas",
    priority: 3,
  },
  {
    title: "LGPD Para Consultórios: O Que Saber Sobre Dados de Pacientes",
    slug: "lgpd-consultorio-odontologico-dados-pacientes",
    primaryKeyword: "LGPD consultório odontológico dados",
    secondaryKeywords: ["compliance dentista", "LGPD consultório odontológico dados dentista"],
    category: "Compliance",
    pillar: "P3",
    searchIntent: "informational",
    outline: ["O que é LGPD", "Dados que coleta e protege", "Consentimento", "WhatsApp e marketing", "CRM: requisitos", "Penalidades"],
    ctaHeading: "Adeque-se à LGPD",
    ctaDescription: "Adequação LGPD para consultórios odontológicos.",
    ctaButton: "Quero Adequação LGPD",
    priority: 3,
  },
  {
    title: "Pare de Planejar Comece a Executar: Ação Supera Perfeição",
    slug: "dentista-acao-supera-perfeicao",
    primaryKeyword: "dentista marketing ação execução",
    secondaryKeywords: ["mentalidade dentista"],
    category: "Mentalidade",
    pillar: "P5",
    searchIntent: "commercial",
    outline: ["Paralisia por análise", "Perfeccionistas ficam para trás", "'Bom o suficiente'", "3 ações para fazer HOJE", "Google Meu Negócio: 30 min", "WhatsApp: 1 template", "Efeito composto"],
    frameworkRef: "Kennedy Wealth Magnet 10: Do Something",
    ctaHeading: "Comece Hoje",
    ctaDescription: "O diagnóstico gratuito é o primeiro passo — leva 30 minutos.",
    ctaButton: "Quero Começar Agora",
    priority: 3,
  },
  {
    title: "Análise de Concorrência: Ferramentas Gratuitas Para Espiar o Rival",
    slug: "analise-concorrencia-dentista-ferramentas",
    primaryKeyword: "análise concorrência dentista ferramentas",
    secondaryKeywords: [],
    category: "Ferramentas",
    pillar: "P1",
    searchIntent: "informational",
    outline: ["Por que monitorar", "Google Maps dos concorrentes", "Facebook Ad Library", "SEO gratuito", "Google Alerts", "Aplicação prática"],
    ctaHeading: "Análise Competitiva",
    ctaDescription: "Análise completa dos seus concorrentes com recomendações.",
    ctaButton: "Quero Analisar Concorrentes",
    priority: 3,
  },
  {
    title: "Sazonalidade: Manter Faturamento Estável o Ano Todo",
    slug: "sazonalidade-odontologia-como-manter-faturamento",
    primaryKeyword: "sazonalidade odontologia faturamento",
    secondaryKeywords: ["gestão dentista", "sazonalidade odontologia faturamento dentista"],
    category: "Gestão",
    pillar: "P2",
    searchIntent: "commercial",
    outline: ["Meses fortes e fracos", "Estratégias para baixa", "Planejamento por trimestre", "Suavizar com pacientes recorrentes", "Manutenção semestral", "Marketing antecipado"],
    problemRef: "2.1 High seasonality",
    ctaHeading: "Estabilize Seu Faturamento",
    ctaDescription: "Planejamento de marketing que suaviza a sazonalidade.",
    ctaButton: "Quero Faturamento Estável",
    priority: 3,
  },
  {
    title: "Marketing Para Odontogeriatria: Alcançar Pacientes Idosos",
    slug: "marketing-dentista-idoso-geriatria",
    primaryKeyword: "marketing odontogeriatria pacientes idosos",
    secondaryKeywords: ["marketing odontogeriatria pacientes idosos dentista"],
    category: "Odontogeriatria",
    pillar: "P4",
    searchIntent: "informational",
    outline: ["Envelhecimento do Brasil", "Quem decide: idoso ou familiar", "Canais: Google + indicação", "Conteúdo empático", "Comunicação acessível", "Parcerias com geriátras"],
    ctaHeading: "Estratégia Para Público Sênior",
    ctaDescription: "Marketing empático para captação de pacientes idosos.",
    ctaButton: "Marketing Para Idosos",
    priority: 3,
  },
  {
    title: "Integridade Como Estratégia: Dentistas Honestos Crescem Mais",
    slug: "integridade-marketing-dentista-confianca",
    primaryKeyword: "integridade marketing dentista confiança",
    secondaryKeywords: ["posicionamento dentista"],
    category: "Posicionamento",
    pillar: "P5",
    searchIntent: "commercial",
    outline: ["Integridade é vantagem competitiva", "Transparência gera confiança", "Preço justo como diferencial", "Avaliações reais", "Compliance CFO", "Efeito longo prazo"],
    frameworkRef: "Kennedy Wealth Magnet 13: Integrity",
    ctaHeading: "Marketing Com Integridade",
    ctaDescription: "Estratégia construída sobre transparência e resultados reais.",
    ctaButton: "Quero Marketing Honesto",
    priority: 3,
  },
  {
    title: "Palavras-Chave Negativas: Lista Que Economiza R$1.000/Mês",
    slug: "google-ads-palavras-chave-negativas-dentista",
    primaryKeyword: "palavras-chave negativas Google Ads dentista",
    secondaryKeywords: [],
    category: "Ads",
    pillar: "P1",
    searchIntent: "informational",
    outline: ["O que são e por que críticas", "Lista completa para odontologia (50+ termos)", "Negativas universais", "Negativas por especialidade", "Revisar semanalmente", "Redução de 20-40% no CPL"],
    ctaHeading: "Auditoria de Palavras-Chave",
    ctaDescription: "Configuramos suas palavras-chave negativas para parar de desperdiçar.",
    ctaButton: "Auditoria de Ads",
    priority: 3,
  },
  {
    title: "Programa de Fidelidade: Transformar Pacientes em Fãs",
    slug: "programa-fidelidade-dentista-retencao-pacientes",
    primaryKeyword: "programa fidelidade dentista retenção",
    secondaryKeywords: [],
    category: "Retenção",
    pillar: "P2",
    searchIntent: "commercial",
    outline: ["Adquirir vs. reter (5x mais caro)", "Manutenção semestral", "Programa VIP", "Indicação com recompensa", "Automação: lembretes e datas", "Medir retenção e LTV"],
    problemRef: "4.4 No VIP programs",
    ctaHeading: "Crie Seu Programa VIP",
    ctaDescription: "Programa de fidelidade que transforma pacientes em promotores.",
    ctaButton: "Quero Programa VIP",
    priority: 3,
  },
  {
    title: "Futuro da Odontologia Digital: 2025 a 2030",
    slug: "futuro-odontologia-digital-2025-2030",
    primaryKeyword: "futuro odontologia digital 2025 2030",
    secondaryKeywords: ["tendências dentista", "futuro odontologia digital 2025 2030 dentista"],
    category: "Tendências",
    pillar: "P3",
    searchIntent: "informational",
    outline: ["IA no diagnóstico", "Teleodontologia", "Impressão 3D", "Marketing automatizado por IA", "Busca por voz", "Personalização via dados", "O que fazer AGORA"],
    ctaHeading: "Prepare-se Para o Futuro",
    ctaDescription: "Estratégia que posiciona seu consultório para o futuro.",
    ctaButton: "Quero Me Preparar",
    priority: 3,
  },
  {
    title: "Citações Locais Para Dentistas: O Que São e Como Construir",
    slug: "citacoes-locais-dentista-nap",
    primaryKeyword: "citações locais NAP dentista SEO",
    secondaryKeywords: [],
    category: "SEO",
    pillar: "P1",
    searchIntent: "informational",
    outline: ["O que são citações locais", "Por que Google usa", "10 diretórios importantes", "Criar e manter consistentes", "Ferramentas de monitoramento", "Impacto de inconsistências"],
    ctaHeading: "Construa Suas Citações",
    ctaDescription: "Cadastro em diretórios estratégicos com NAP consistente.",
    ctaButton: "Quero Citações Locais",
    priority: 3,
  },
  {
    title: "Marketing Para ATM/DTM: Captar Pacientes Com Disfunção",
    slug: "marketing-dentista-atm-disfuncao-temporomandibular",
    primaryKeyword: "marketing DTM ATM dentista",
    secondaryKeywords: ["atm/dtm dentista"],
    category: "ATM/DTM",
    pillar: "P4",
    searchIntent: "informational",
    outline: ["Paciente de DTM: dor crônica", "Palavras-chave de sintomas", "Conteúdo educativo como funil", "Google Ads para sintomas", "Parcerias com fisioterapeutas", "Posicionamento como especialista"],
    ctaHeading: "Marketing Para DTM",
    ctaDescription: "Captação de pacientes de DTM que não sabem que precisam de dentista.",
    ctaButton: "Captar Pacientes DTM",
    priority: 3,
  },
  {
    title: "Prova Social: 7 Formas de Mostrar Que Você É a Melhor Escolha",
    slug: "dentista-prova-social-como-construir",
    primaryKeyword: "prova social dentista consultório",
    secondaryKeywords: ["conversão dentista"],
    category: "Conversão",
    pillar: "P5",
    searchIntent: "commercial",
    outline: ["Pessoas seguem o que outros aprovam", "Avaliações Google", "Depoimentos em vídeo", "Números e métricas", "Certificações", "Prêmios", "Presença na mídia", "Bastidores"],
    frameworkRef: "Hormozi: Social proof / Kennedy: Demonstration",
    ctaHeading: "Construa Sua Prova Social",
    ctaDescription: "Sistema de prova social que converte visitantes em pacientes.",
    ctaButton: "Quero Prova Social",
    priority: 3,
  },
  {
    title: "Lead Não Responde no WhatsApp? 5 Estratégias Para Recuperar",
    slug: "whatsapp-paciente-nao-responde-como-recuperar",
    primaryKeyword: "lead WhatsApp não responde dentista",
    secondaryKeywords: ["conversão dentista"],
    category: "Conversão",
    pillar: "P2",
    searchIntent: "commercial",
    outline: ["Por que param de responder", "Mensagem genérica sem personalização", "Valor não cobrança", "Prova social oportuna", "Lembrete com prazo", "Mudança de canal", "Reengajamento via ads", "Templates"],
    problemRef: "2.2 Leads who don't respond",
    ctaHeading: "Recupere Leads Perdidos",
    ctaDescription: "Templates e automação para recuperar leads que sumiram.",
    ctaButton: "Quero Recuperar Leads",
    priority: 3,
  },
  {
    title: "Marketing Odontológico em Portugal: Oportunidades Para Brasileiros",
    slug: "marketing-odontologico-portugal-expansao",
    primaryKeyword: "marketing odontológico Portugal dentista brasileiro",
    secondaryKeywords: ["internacional dentista"],
    category: "Internacional",
    pillar: "P3",
    searchIntent: "informational",
    outline: ["Mercado português", "Diferenças regulatórias", "SEO em Portugal", "Poucos investem em digital", "Adaptar estratégias", "LK Digital em Portugal"],
    ctaHeading: "Marketing em Portugal",
    ctaDescription: "Expandimos estratégias para dentistas brasileiros em Portugal.",
    ctaButton: "Quero Expandir Para Portugal",
    priority: 3,
  },
  {
    title: "Checklist Definitivo: 50 Ações Para Agenda Cheia",
    slug: "checklist-completo-marketing-digital-dentista",
    primaryKeyword: "checklist marketing digital dentista completo",
    secondaryKeywords: ["guia dentista"],
    category: "Guia",
    pillar: "P1",
    searchIntent: "informational",
    outline: ["Presença digital (10 ações)", "SEO local e Maps (10 ações)", "Conteúdo e redes (10 ações)", "Anúncios pagos (10 ações)", "Conversão e retenção (10 ações)", "Download PDF"],
    ctaHeading: "O Checklist Completo",
    ctaDescription: "50 ações organizadas por prioridade para sua agenda ficar cheia.",
    ctaButton: "Baixar Checklist e Começar",
    priority: 3,
  },
];